# Site wide configuration

title:            Szymon Laszczyński
locale:           pl_PL
url:              http://localhost:4000 # simon-joseph.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Szymon Laszczyński
  avatar: me.jpg
  bio: "Describe your self."
  email: 
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: szymonlaszczynski
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: simon-joseph
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  behance: szymonlaszczynski

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
